language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false


install:
  - composer install --prefer-source --no-interaction

script: ./vendor/bin/phpunit

after_script:
  - ./bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
